### ISSUE TITLE
gradual, and increasing, acceleration

### ISSUE THREAD

**Issue by sambishop** [wunderkammer-laboratory/ackermann_vehicle#2]
This model has been fantastic, and I am able to use it successfully, but I am also having a small issue with it.  I thought I'd track it here in case others run into it.

A simple `roslaunch ackermann_vehicle_gazebo ackermann_vehicle.launch` works, of course, and everything looks great.  But what I've found when feeding the position and acceleration data into the robot_localization Kalman filters is that the model is creeping along in a positive X direction and picking up speed.  The movement is visible after a few minutes.  Here's how to see what I'm talking about, without waiting that long:

`rostopic echo '/ackermann_vehicle/gazebo/model_states/pose[1]' | grep -A 1 position | awk '/x/ { print $2 }' | tee x_location.csv`

This is with Gazebo 2.2.3.  I don't know if the problem is with Gazebo, the model, or controllers, but I will add more details as I can.

**Comment by wunderkammer-laboratory** [comment]
I commented out the ackermann_controller node in ackermann_vehicle.launch, and commented out the gazebo_ros_control plugin in em_3905.urdf.xacro. The vehicle still moves. In fact, it moves much faster, since there is no velocity controller to keep the velocity near zero. It appears that Gazebo is causing the unintended motion. To fix the problem, you can try using a different Gazebo simulation engine, such as Bullet. You can also take em_3905.urdf.xacro, remove the gazebo_ros_control plugin element and its enclosing gazebo element, then post the result to answers.gazebosim.org, along with a launch file. In the post, ask why the vehicle moves when simulated in Gazebo 2.2.3.

Unless you are able to find perfect PID parameters, the velocity controller will maintain a velocity arbitrarily near the desired velocity, but not *exactly* the desired velocity. Furthermore, using a velocity controller to maintain a position is unlikely to work. For example, imagine that the vehicle is on an incline. The velocity controller will not output a nonzero effort until the vehicle's velocity is nonzero, which means that its position has changed. To maintain a position, the controller would have to output an effort that not only stops the vehicle, but moves it back to its previous position. The nonzero velocity caused by the movement would make the controller output a new nonzero effort value in the next controller cycle. Depending on the controller's PID parameters, the vehicle probably will creep slowly uphill or downhill.

Control of the vehicle's position is intended to be accomplished with odometry and controller nodes. The odometry node (which could be an enhanced version of ackermann_controller.py) would publish the vehicle's pose and velocity in a nav_msgs/Odometry message to the "odom" topic. The controller node would subscribe to the odometry topic, then publish velocity commands to ackermann_cmd. The commands would maintain the vehicle's desired position and velocity.

**Comment by sambishop** [comment]
Thanks for looking into this.  I would be happy to dig into this further, but there is a competition coming up--much too fast--in June, and that has me pretty busy.  But after that, if not before, I will dig into this further.

By the way though, when I was looking into this, I spent most of my time thinking that the car was sliding, at a constant rate.  So of course my focus was on Gazebo.  It wasn't until I was prepping to submit this issue that I let it run long enough to see the wheels turning and the car speeding up.  That makes me think it's an error accumulating in the controller.

One more thing, for the benefit of anyone besides Jim that might be reading this.  **This is a tiny issue**.  Don't worry, this is a solid model, and I would recommend starting here instead of attempting to build one from scratch like I did!

**Comment by sambishop** [comment]
Well, it's August, and I still haven't had time to look into this further.  For better or for worse, my spare time is being taken up by paying gigs that don't involve self-driving cars.  You're welcome to close this if you'd like.  Thanks again!
